### ISSUE TITLE
"@" special character missing

### ISSUE THREAD

**Issue by N0ury** [Vogtinator/pyWrite#2]
When I type special characters, they are all same as when using console.
All but one. When I type CTRL-EE, '&' is displayed, not '@'.

**Comment by Vogtinator** [comment]
To get @, you need to press Ctrl+Shift+EE. Which console are you referring to?

**Comment by N0ury** [comment]
Oh thanks, it works.
For all other characters I need to press only SHIFT or CTRL. That's why I couldn't get @.
When saying console, I was talking about ndless console.
I was in fact actually referring to "nio_ascii_get" function.

**Comment by Vogtinator** [comment]
Right, pyWrite uses `nio_ascii_get` as well: https://github.com/Vogtinator/pyWrite/blob/6536dc587f4e563d9231ed5c2b855ca56d3db76f/editortask.cpp#L108

So this might just be two different versions of nspire-io.
