### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by jkcoxson** [Vogtinator/pyWrite#3]
Is there instructions somewhere to compile this?
I'm currently following the instructions on hackspire to install the SDK and toolchain, but I am wondering if this is the way to compile it.
Also, is there a binary newer than the one on TI-calc? Your post shows that there is no save support but a commit here shows that it was implemented.

**Comment by Vogtinator** [comment]
After the SDK and toolchain are built, just run `make` to build it. I just did that here and it built successfully:
[pyWrite.zip](https://github.com/Vogtinator/pyWrite/files/5278436/pyWrite.zip)

**Comment by jkcoxson** [comment]
Thanks, I got it built. Thanks for all your work with the NSpire!
