### ISSUE TITLE
Can´t compile with ndless-sdk

### ISSUE THREAD

**Issue by NunexGTX** [Vogtinator/pyWrite#4]
I tried compiling this app for myself so that I could have the ability to save the files on my calculator and this error is happening while compiling:

```
nspire-ld main.o pythonhighlighter.o cursortask.o dialogtask.o browsertask.o settingstask.o task.o font.o editortask.o widget.o nGL/gl.o nGL/fastmath.o nGL/texturetools.o nGL/gldrawarray.o -o pyWrite.elf -Ofast -I nGL -I . -Wall -W -marm -ffast-math -mcpu=arm926ej-s -fno-math-errno -fomit-frame-pointer -flto -fno-rtti -fgcse-sm -fgcse-las -funsafe-loop-optimizations -fno-fat-lto-objects -frename-registers -fprefetch-loop-arrays -Wno-narrowing -ffunction-sections -fdata-sections -lm -lnspireio -Wl,--gc-sections
arm-none-eabi-ld: cannot find -lnspireio
collect2: error: ld returned 1 exit status
make: *** [Makefile:27: pyWrite.elf] Error 1
```

Does anyone have any clue for the solution?

Thank you in advance

**Comment by Vogtinator** [comment]
Does `Ndless/ndless-sdk/lib/libnspireio.a` exist?

If not, what happens if you run `make` in the `Ndless` checkout again?

**Comment by NunexGTX** [comment]
Sorry for taking to long to answer.

> Does `Ndless/ndless-sdk/lib/libnspireio.a` exist?
> 
> If not, what happens if you run `make` in the `Ndless` checkout again?

It seems that `Ndless/ndless-sdk/lib/libnspireio.a` doesn´t exist.

And if I run `make` in Ndless directory (not sure if that´s what you asked), I get this error:

```
nspire-gcc -Wall -W -marm -Os -c ndless-sdk/thirdparty/freetype2/builds/windows/ftdebug.c -o ndless-sdk/thirdparty/freetype2/builds/windows/ftdebug.o
ndless-sdk/thirdparty/freetype2/builds/windows/ftdebug.c:44:10: fatal error: ft2build.h: No such file or directory
   44 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:30: ndless-sdk/thirdparty/freetype2/builds/windows/ftdebug.o] Error 1
```

Just to make sure is this what you asked, before running make and this appearing, I open the terminal and type `cd Ndless`

**Comment by Vogtinator** [comment]
Ok, so building the SDK failed.

Apparently FT2 thinks it should build for windows, which won't work.

What's the output of `rm ndless-sdk/thirdparty/freetype2/config.mk && make -C ndless-sdk/thirdparty`?

**Comment by NunexGTX** [comment]
Here is the output:

`rm: cannot remove 'ndless-sdk/thirdparty/freetype2/config.mk': No such file or directory
`

Which when I go to that directory I can confirm that the file does not exist. 

![image](https://user-images.githubusercontent.com/74361788/118479429-e97f7d80-b708-11eb-9cb3-b0ad9bff6b48.png)

Yeah, probably messed up the installation

**Comment by Vogtinator** [comment]
Ok, then just the `make -C ndless-sdk/thirdparty` should do.

**Comment by NunexGTX** [comment]
Now if I try to compile pyWrite again it shows this:

`nspire-ld main.o pythonhighlighter.o cursortask.o dialogtask.o browsertask.o settingstask.o task.o font.o editortask.o widget.o nGL/gl.o nGL/fastmath.o nGL/texturetools.o nGL/gldrawarray.o -o pyWrite.elf -Ofast -I nGL -I . -Wall -W -marm -ffast-math -mcpu=arm926ej-s -fno-math-errno -fomit-frame-pointer -flto -fno-rtti -fgcse-sm -fgcse-las -funsafe-loop-optimizations -fno-fat-lto-objects -frename-registers -fprefetch-loop-arrays -Wno-narrowing -ffunction-sections -fdata-sections -lm -lnspireio -Wl,--gc-sections
arm-none-eabi-ld: cannot find -lndls
arm-none-eabi-ld: cannot find -lsyscalls
collect2: error: ld returned 1 exit status
make: *** [Makefile:27: pyWrite.elf] Error 1
`

:(

**Comment by Vogtinator** [comment]
Yes, because the SDK is still not built. Only when that's done, you can build applications.

**Comment by Vogtinator** [comment]
What was the output of `make -C ndless-sdk/thirdparty`?

**Comment by NunexGTX** [comment]
> What was the output of `make -C ndless-sdk/thirdparty`?

It ended with something saying "leaving directory" and some directory. But I ended up deleting the VM, so I'm reinstalling the whole the SDK again. Running make to compile pyWrite didn't work after doing that. Once I try to do it again, I see if the issue persists or if it works, but it will take a couple of days, because I'm a bit busy.

**Comment by NunexGTX** [comment]
Ok. It was a really bad SDK installation and reinstalling and doing from scratch it worked. Not sure what went wrong with the other one and maybe it could be done without reinstalling the whole SDK. But thank you
